### PR TITLE
Resolve block binding/class definition race condition

### PR DESCRIPTION
**Pull request by estolfo**
This is an attempt to resolve an occasional error on JRuby:
```
NoMethodError: undefined method `enqueue' for #<ElasticAPM::Agent:0xc9518ee>
 # ./lib/elastic_apm/agent.rb:77:in `block in initialize'
```

### CODE REVIEW

**Comment by mikker** [comment]
An issue could be threads as the `initialize` is called inside a mutex lock in `self.start` and these new ones might be called at the same time from different threads?

**Comment by estolfo** [comment]
The `instrumenter` and `metrics` objects are initialized lazily when the `start` method is called, which is still in the mutex [here](https://github.com/elastic/apm-agent-ruby/blob/master/lib/elastic_apm/agent.rb#L46)
You bring up a good point - for example, one obscure issue could be that someone would call `current_transaction` on the agent from another thread, which would in turn initialize the instrumenter at the same time that the `start` method is being called. So this isn't a good solution...I'll investigate more.

**Comment by estolfo** [comment]
As a note..the tests have passed so it's likely the JRuby error is due to a race condition between the file being loaded and the block binding being defined.

**Comment by mikker** [comment]
You could use the same lock as in `self.start` to lock the lazy initialization. Similar to the quite verbose but safe `start`:
```ruby
def metrics
  return @metrics if @metrics

  MUTEX.lock
    @metrics = Metrics.new(...)
  end
end
```

**Comment by estolfo** [comment]
You wouldn't be able to use the same lock from `self.start` though because you'd get a recursive locking error.

**Comment by estolfo** [comment]
I tried another approach - allocating the object and then initializing it directly. Let's see if it has an effect...

**Comment by mikker** [comment]
Only if `start` references `metrics`?

**Comment by estolfo** [comment]
The class `start` method calls the `start` method on the `@instance` within the lock and `metrics` would be referenced from there.

**Comment by mikker** [comment]
fwiw, I used to pass the agent along in the initializers. Moved to the _callback_ based approach to not have to make an agent for them when testing and decouple a bit. Worth moving back if it fixes it.

**Comment by estolfo** [comment]
@mikker Makes complete sense - both designs are valid. Let's see what the JRuby team says on my issue and decide from there how we can work around it.

**Comment by mikker** [comment]
This one can be closed too?

**Comment by estolfo** [comment]
yes, I'll follow up on the JRuby ticket

**Pull request closed without merging**
