### PR TITLE
Add JRuby 9.2 to test matrix

### PR DESCRIPTION
**Pull request by mikker**

### CODE REVIEW

**Comment by mikker** [comment]
Failing due to this https://github.com/jruby/jruby/issues/5200.

**Comment by mikker** [comment]
Not really sure what to do here. @simitt any suggestions? Only thing I see is write conditional tests around it. Not really a real solution.

**Comment by simitt** [comment]
Looking at the test, what is wrong (logically) with having `actual_exception` as function name? It really is the function that causes the error. Could you explain why it would be better to have `/` here as function name?

**Comment by mikker** [comment]
I don't want the _right_ answer. I just want consistency between the ruby runtimes/versions. This is JRuby 9.1 having one thing as the top-most line in the backtrace and JRuby 9.2 having another. I don't feel like I can do anything about that fact so what I'm wondering is how do I make our specs work around that. 😄

**Comment by mikker** [comment]
jenkins, retest this please

**Comment by mikker** [comment]
jenkins, retest this please

**Comment by mikker** [comment]
jenkins, retest this please

**Pull request merged**
