### PR TITLE
Fix delayed job class name

### PR DESCRIPTION
**Pull request by hashwin**
Fixes https://github.com/elastic/apm-agent-ruby/issues/833
@mikker

### CODE REVIEW

**Comment by mikker** [comment]
jenkins, please run the tests

**Comment by mikker** [comment]
jenkins, please run the tests

**Comment by mikker** [comment]
This is great, @hashwin!

**Comment by mikker** [comment]
Test error is unrelated

**Comment by mikker** [comment]
jenkins, please run the tests

**Comment by mikker** [comment]
@hashwin Do you feel like this is ready to go?

**Comment by hashwin** [comment]
@mikker yep I think this should cover it.

**Comment by mikker** [comment]
💙💚💛💜❤️

**Pull request merged**
