### PR TITLE
Run worker in run loop

### PR DESCRIPTION
**Pull request by OpakAlex**
For sidekiq we have one issue, log term work with some load, we got message:
```
2018-11-20T13:13:09.995Z 8 TID-grgn7ph10 WARN: [ElasticAPM] Worker died with exception: #<Zlib::GzipFile::Error: closed gzip stream>
 WARN: [ElasticAPM] Queue is full (256 items), skipping…
```

This PR fixed issues with sidekiq.

### CODE REVIEW

**Comment by mikker** [comment]
Thank you for providing this @OpakAlex. For anyone else coming to this' sake: We're investigating this issue but haven't concluded anything yet. If you experience anything like this, please let us know.

**Comment by mikker** [comment]
Why would the span be `nil` there? I'd only expect it to be if the agent was nil or the current transaction was nil but there are guard clauses that check for both of those.

Are you by any chance using S3 in your Sidekiq jobs and that could be why they keep dying?

**Comment by OpakAlex** [comment]
But it's not depends on issue with died apm. This another one ;) Because in my case i download s3 data once in 24 hours.

**Comment by OpakAlex** [comment]
One more issue @mikker , i detected memory leaks for my jobs. This happens after update apm gem. Any ideas why?

**Comment by mikker** [comment]
@OpakAlex Could it be due to all the worker restarts from your eternal loop-change?

**Comment by OpakAlex** [comment]
@mikker haha 100% YES, because without this fix it works onl +-1hour ;) For this time i didn't have memory usage data..... it works more, my limits 1070mb for sidekiq container. So it just working more time and reach this limit, than kubernetes restart container.

**Comment by OpakAlex** [comment]
I think the best idea it's just port to v1.1..... because we didn't have any issues (only big payload)

**Comment by OpakAlex** [comment]
So i think the best idea for me, just disable apm for sidekiq, untill you will do port to v1.1. Because i really don't have time to play this game. APM itself so good tool, but now it's a pain for me.

**Comment by mikker** [comment]
I'm sorry to hear. I am, like I noted before, running this exact combination, Puma and Sidekiq, myself with no trouble.

Before you go, what's your version of Ruby, Rails and Sidekiq? Could you share your Gemfile? You know my email if you don't want to share it here. Would help a lot with the debugging.

**Comment by OpakAlex** [comment]
done @mikker ,i am trying one more fix. will tell you result.

**Comment by OpakAlex** [comment]
@mikker looks like `run_forever` make leaks for memory. i will try to remove this option. and check what happens.

**Comment by OpakAlex** [comment]
@mikker so memory leaks fixed. But events stop sending after +-1h... We have same what we had 2 days ago ;)

**Comment by mikker** [comment]
Yes, and that was the gzip streams suddenly being closed, right? That was the reported error that shut down the workers?

**Comment by mikker** [comment]
Got it 👍 

Sampling can bring down the overhead of the agent when used with high-traffic apps. `config.transaction_sample_rate = 0.5` for example would mean _include spans with this transaction if `rand >= 0.5`_

**Comment by OpakAlex** [comment]
ok, i will try this in config and will tell result.

**Comment by mikker** [comment]
Sure, you can – but it wasn't a suggestions to fix your problem 😄

**Comment by OpakAlex** [comment]
yes @mikker. 
So i have some statistic, i have 2 apps in production (with sidekiq workers).
One it's a OSS app: huginn. All works perfect. (sidikeq too)
And another one (Gemfile was send to you) where issue with sidekiq reports.
I think issue maybe with some gems... or...
what do you think @mikker ?

**Pull request closed without merging**
