### PR TITLE
fix: rails master has been renamed to main (cont.)

### PR DESCRIPTION
**Pull request by mikker**
Continued from #939

### CODE REVIEW

**Comment by mdelapenya** [comment]
Oh, I sent a commit on top of mine, but it seems this one resolves it better. Will close my PR, thanks!

**Review by mdelapenya — APPROVED** [review]

**Comment by mikker** [comment]
This fails while building a native package on some jruby images. Do they have `gcc` or similar available? `build-essential` or what have you?

**Comment by mdelapenya** [comment]
> This fails while building a native package on some jruby images. Do they have `gcc` or similar available? `build-essential` or what have you?

The jruby images are built within this repository, in https://github.com/elastic/apm-agent-ruby/tree/master/.ci/docker/jruby, but I do not see any reference to `gcc` or `build-essential`. Do you think that updating them with your needs would fix this build problem? If it fixes it, we should push them again to the container registry.

**Comment by mikker** [comment]
I don't know honestly, I just saw that building the native extension failed. I'll have to try it out locally.

**Pull request merged**
