### PR TITLE
Move framework specific requires to spies

### PR DESCRIPTION
**Pull request by mikker**
Our current solution depends on the `elastic-apm` gem to be loaded _after_ Grape or Sinatra.

This PR uses the already present mechanism of hooking into require to make sure to load regardless of gem order.

### CODE REVIEW

**Comment by estolfo** [comment]
Looks good 👍
Do we have to make any changes in the tests?

**Comment by mikker** [comment]
My hope was that it would _Just Work™_ but let's see.

**Comment by estolfo** [comment]
Some more comments:
I think we have to add `grape` to [here](https://github.com/elastic/apm-agent-ruby/blob/master/lib/elastic_apm/config.rb#L112-L127)
We can also remove [these](https://github.com/elastic/apm-agent-ruby/blob/master/lib/elastic_apm.rb#L27-L28) lines.

**Comment by mikker** [comment]
On second thought, this doesn't cut it. As the spies aren't required before here https://github.com/mikker/apm-agent-ruby/blob/af2357eb09ef68e5469facdf50752a2639a85316/lib/elastic_apm/agent.rb#L103-L106 `ElasticAPM::Grape` won't be available before starting the agent.

So, do we add `require 'elastic_apm/grape'` to the installation instructions (maybe, probably, breaking change?) or keep it all as is?

I think I'd say option 2.

**Comment by estolfo** [comment]
I would hesitate to add a breaking change for something no one has complained about. So maybe we should just leave it as-is?

**Comment by mikker** [comment]
Wholeheartedly agree, closing.

**Pull request closed without merging**
