### PR TITLE
Warn that starting the agent for a Sintra app using app config arg is deprecated

### LINKED ISSUE #909: Warn users of the removal of the config app arg in favor of Rails.start and Sinatra.start
Suggest the `Rails|Sinatra.start` API in the 3.x branch with a notice of upcoming removal in 4.0.

Update: We only document starting a rails app via `ElasticAPM::Rails.start(...)` or via the Railtie, so we don't have to create a deprecation warning. ([ref](https://www.elastic.co/guide/en/apm/agent/ruby/current/api.html#rails-start))
For Sinatra, we do document `ElasticAPM.start(app: MySinatraApp)` ([ref](https://www.elastic.co/guide/en/apm/agent/ruby/current/configuration.html#_sinatra_and_rack)) so we have to warn about the deprecation.

### PR DESCRIPTION
**Pull request by estolfo**
Resolves #909

### CODE REVIEW

**Comment by estolfo** [comment]
I think I should warn about using the `app` config arg instead.

**Comment by estolfo** [comment]
Actually, I think this makes sense. If we warn anytime `app` is set on a config, it will create noise for users who use a Railtie and who don't intentionally use the `app` option.

**Comment by mikker** [comment]
Remind me what the benefit is here? Could we keep on supporting the old way? I just think, if there's no clear benefit in the end for the user, we are just being a nuisance by making them have to change their app with no clear benefit to them (nor to us, in the end)?

**Comment by estolfo** [comment]
I was hoping to consolidate the "special" behavior for each applications type into the application's module. For example, I was trying to avoid having [these lines](https://github.com/elastic/apm-agent-ruby/blob/master/lib/elastic_apm/config.rb#L356-L365) in the config and instead have them in the `Rails` module. It also seems cleaner to suggest only one way to start the agent for a given app type (Sinatra, Rails, Grape)

**Comment by estolfo** [comment]
Closing this as we probably aren't going to deprecate the app in the config

**Pull request closed without merging**
