### PR TITLE
Fix variable typo in instrumenter

### PR DESCRIPTION
**Pull request by estolfo**
I noticed this small variable typo in the instrumenter when reviewing the code changes made in the last few months.

### CODE REVIEW

**Comment by mikker** [comment]
Yikes! Good catch.
Did you commit this with a non-Elastic email address? Why's the CLA checker saying no?

**Comment by estolfo** [comment]
I'm resolving it with infra now...there was a script in June that removed a bunch of us from the elastic org and I didn't get it corrected for myself as I was out.

**Comment by mikker** [comment]
I remember that morning where everyone was fired 😅

jenkins, please run the tests

**Comment by mikker** [comment]
jenkins, please run the tests

**Review by mikker — APPROVED** [review]

**Pull request merged**
