### PR TITLE
Return Error object from report

### PR DESCRIPTION
**Pull request by mikker**
Suggested in https://discuss.elastic.co/t/make-elasticapm-report-return-an-error-or-error-id-instead-of-true/196504.

### CODE REVIEW

**Comment by greyblake** [comment]
Thanks for that quick reply and for the pull request.
I'd like to let you know that at the moment `ElasticAPM::Error` is marked with `@api private`.
Since we're know exposing `Error`, should `@api private` be removed as well? 
(I am not sure what's correct, but I'd like to bring your attention to this)

**Comment by mikker** [comment]
You are right that we probably should make the resource objects public, like `Error`, `Transaction`, `Span` perhaps even `MetricSet` and `Metadata`. That does make the scope of this PR much larger though.

**Comment by greyblake** [comment]
@mikker Would it be OK for you then just to return `error.id` ?
This would be enough to satisfy my use case (rendering error id in response body) at the same time we can keep `Error` private.

**Comment by mikker** [comment]
That's a very nice alternative to keep this PR small 👍

**Comment by greyblake** [comment]
@mikker Thank you!

**Pull request merged**
