### PR TITLE
feat(jenkins): new notifications and reports to Elasticsearch

### PR DESCRIPTION
**Pull request by kuisathaverat**
* new notifications and reports to Elasticsearch
Screenshot 2019-06-05 at 12 57 54

### CODE REVIEW

**Comment by mikker** [comment]
Looks good! Will we have a dashboard in a Kibana somewhere since it's going to ES?

**Comment by kuisathaverat** [comment]
yep, in the benchmarks Elastic search there is a dashboard, right now it is pretty simple but the idea it is to put more stuff on it.

**Comment by kuisathaverat** [comment]
@mikker Is possible to merge this one?

**Comment by mikker** [comment]
Yes, I'll force it through 👍

**Pull request merged**
