### PR TITLE
Only support auto Sinatra app configuration via ElasticAPM::Sinatra.start

### PR DESCRIPTION
**Pull request by estolfo**
Use `ElasticAPM::Sinatra.start(MySinatraApp, ...)` instead of `ElasticAPM.start(app: MySintraApp, ...)`

### CODE REVIEW

**Review by mikker — COMMENTED** [review]
If we were _reeaally_ nice to folks, we'd start suggesting this new api in the 3.x branch with an upcoming removal notice, then remove it in 4.0 first?

**Comment by estolfo** [comment]
Sure, we should probably do it for rails also. I can open a PR against master for that.

**Comment by estolfo** [comment]
In the meantime, can we merge this into `next` if you approve of this PR? That way, I can update #905 to include these changes.

**Review by mikker — APPROVED** [review]
Yes!

**Pull request merged**
