### PR TITLE
If APM server will return cache-control: private, max-age=0 header, w…

### PR DESCRIPTION
**Pull request by arekk**
It relates to issue #1282 

In short words - APM server is behind a reverse proxy - if APM server is unavailable, reverse proxy respond with 530 HTTP error and is adding a header:
```
cache-control: private, max-age=0, no-store, no-cache, must-revalidate, post-check=0, pre-check=0
```

Probably scenario in that case is: 

method z`ElasticAPM::CentralConfig#schedule_next_fetch` is called once `ElasticAPM::CentralConfig#fetch_and_apply_config` gets HTTP error. In `ElasticAPM::CentralConfig#schedule_next_fetch`  max-age is used to determine a delay for next config fetch. It's 0 in that point, so fetch_and_apply_config is called immediately, it gets error and max-age=0 again, and again.

Suggested fix in this pull request. Not tested yet.

### CODE REVIEW

**Comment by jaggederest** [comment]
Hi @arekk any news on testing this? I plan to reproduce this myself before merge, but it would be great to have confirmation from you. Also, can you sign the CLA? Thank you!

**Comment by arekk** [comment]
> Hi @arekk any news on testing this? I plan to reproduce this myself before merge, but it would be great to have confirmation from you. Also, can you sign the CLA? Thank you!

Sorry @jaggederest - didn't know you're waiting. I've tested changes, also on production environment with forked gem. It works as expected also survived agent unavailability. CLA signed.

**Comment by jaggederest** [comment]
No problem thanks for the PR! I'm glad this fixed your issue, relatively minor change. It should be merged sometime this week and in the next agent version 👍

**Comment by jaggederest** [comment]
run elasticsearch-ci/docs

**Comment by jaggederest** [comment]
Hi @arekk sorry for all the spam, can you rebase? There was a change in an underlying library we use for testing, which is now pinned. If you rebase to `main` it should fix the tests and I will merge 👍 I would happily do it for you, but you're pulling from your own repo. Thanks again for the contribution.

**Comment by arekk** [comment]
> Hi @arekk sorry for all the spam, can you rebase? 

Hi @jaggederest, no prob, I've synced my fork.

**Comment by jaggederest** [comment]
run elasticsearch-ci/docs

**Comment by jaggederest** [comment]
Hi @arekk I dropped a PR into your repo that updates the minimum time, we clarified the spec on our end 👍

**Comment by jaggederest** [comment]
run elasticsearch-ci/docs

**Pull request merged**
