### PR TITLE
Add thread-safety stress test for Metrics

### PR DESCRIPTION
**Pull request by mikker**
... doesn't fail. Can you spot anything to improve, @estolfo?

### CODE REVIEW

**Comment by mikker** [comment]
@kuisathaverat Still getting coverage comments here?

**Comment by kuisathaverat** [comment]
brrrr!!! https://github.com/elastic/apm-agent-ruby/blob/master/.codecov.yml#L32, I will see what happens

**Comment by kuisathaverat** [comment]
my fault, the file name should be codecov.xml. It is resolved in the following commit 
https://github.com/elastic/apm-agent-ruby/commit/7dd395ef84ac3c79d4b2e5bfe59a2de8a26f4a1b

**Comment by estolfo** [comment]
I was going to review this but then saw the test failures. I think the latest (rails metrics) test is great because we're now getting some indication that something is awry. I guess it's not worth "approving" this PR yet, as it can be used to try to figure out why metrics are getting dropped.

**Comment by mikker** [comment]
Superseded by #699

**Pull request closed without merging**
