### PR TITLE
Remove secrets from cookies for error reporting

### PR DESCRIPTION
**Pull request by dalibor**
Sensitive data are not filtered from cookies for the errors reporting.

### CODE REVIEW

**Comment by dalibor** [comment]
I've signed the Individual Contributor License Agreement. Can you please re-build this PR, merge and release?

**Comment by mikker** [comment]
Hi @dalibor! Thank you for discovering this. Looks good 👍

**Comment by mikker** [comment]
jenkins, run the tests

**Comment by dalibor** [comment]
Hi @mikker — thank you! I see the build is failing, anything I can do my side?

**Comment by mikker** [comment]
The error is not related, no worries.

**Comment by mikker** [comment]
I've included this in v3.10.1 which is on the way through the pipes.

Thanks! 💙💚💛💜❤️

**Comment by dalibor** [comment]
@mikker Thank you!

**Pull request merged**
