### PR TITLE
Fix Faraday host parsing when building request in block

### LINKED ISSUE #336: ArgumentError (bad argument (expected URI object or URI string)) with Faraday
Hello,

I got the error when request a url which set in the block

```ruby
client = Faraday.new
client.get do |req|
  req.url('http://example.com/page.html')
end
```

ArgumentError (bad argument (expected URI object or URI string)):

### PR DESCRIPTION
**Pull request by cwheart**
Closes #336

### CODE REVIEW

**Comment by mikker** [comment]
Hi @cwheart! Thanks for this. I need you to sign our CLA before I can merge. When you do I'll be happy to include this 👍

**Comment by mikker** [comment]
jenkins, test this please

**Comment by cwheart** [comment]
I am sorry for the test result, I had fix the problem, what should i do now?

**Comment by mikker** [comment]
It seems our CLA tool is broken. I'm asking around to get it going again. Apologies – I'll let you know when it's back.

**Comment by mikker** [comment]
Everything seems to be running again. You don't need to do anything. Thanks for your help!

**Pull request merged**
