### PR TITLE
Set view paths from ActionController::Base (#822)

### LINKED ISSUE #822: Views provided by engines appear in trace samples as "Absolute Path"
## Describe the bug
The problem is `self.__view_paths = app.config.paths['app/views'].existent` in `config.rb`. This only adds paths of the main application. I could not figure out a way to configure this variable and hence the underscores i guess it is not meant to be configurable :sweat_smile: 

For the time being I just patched it like this

```rb
initializer 'patch_elastic_apm', before: 'elastic_apm.initialize' do
  ::ElasticAPM::Config.prepend(Module.new do
    def set_rails(app)
      super
      self.__view_paths = ::ActionController::Base.view_paths.map(&:to_s)
    end
  end)
end
```

## Steps to reproduce

Mount a rails engine.

## Expected behavior

Partials of the engine show up.

## Environment

- **OS**: Linux
- **Framework and version**: Rails 5.2.4
- **APM Server version**: 7.8.0
- **Agent version**: elastic-apm (3.8.0)

### PR DESCRIPTION
**Pull request by f-mer**
## What does this pull request do?

Resolves #822 

## Checklist

- [ ] I have signed the [Contributor License Agreement](https://www.elastic.co/contributor-agreement/). 
- [x] My code follows the style guidelines of this project (See `.rubocop.yml`)
- [x] I have rebased my changes on top of the latest master branch

- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing [**unit** tests](https://github.com/elastic/apm-agent-ruby/blob/master/CONTRIBUTING.md#testing) pass locally with my changes

- [ ] I have made corresponding changes to the documentation
- [ ] I have updated [CHANGELOG.asciidoc](CHANGELOG.asciidoc)
- [ ] I have updated [supported-technologies.asciidoc](docs/supported-technologies.asciidoc)
- [ ] Added an API method or config option? Document in which version this will be introduced

### CODE REVIEW

**Comment by mikker** [comment]
Perfect! I need you to sign our [CLA](https://www.elastic.co/contributor-agreement) before I can merge.

**Comment by mikker** [comment]
jenkins, run the tests

**Comment by mikker** [comment]
@f-mer I want to include this but can't without you signing the CLA. It only takes a minute 😊

**Comment by f-mer** [comment]
Sorry for the delay but I feel not comfortable signing something in a rush.
Writing code is the easy part, evaluating the eventual consequences of an
agreement in a foreign language not so.

I might not sign the CLA in the near future.
Feel free to close this pull request.

Am Do., 2. Juli 2020 um 15:48 Uhr schrieb Mikkel Malmberg <
notifications@github.com>:

**Comment by mikker** [comment]
Ok. I respect that. I would love to include your change and appreciate your work, I just can't merge it with your credit as long as you haven't signed.

If I create a separate PR with the same change, you won't get the contribution credit, but we still get the fix. Would you be ok with that solution?

**Comment by mikker** [comment]
Implemented in #839. Thank you for pointing me to the issue, @f-mer!

**Pull request closed without merging**
