### PR TITLE
Support chained exceptions (copy for Jenkins, replaces #481)

### PR DESCRIPTION
**Pull request by estolfo**
Copy of #481 
Opening this PR to retest on Jenkins.
See the above PR for comments/reviews.

Update:
Waiting to find out if not including the stacktrace for chained exceptions, and only at the top-level, is ok with the UI: https://github.com/elastic/kibana/issues/43701
The other questions in the above Kibana ticket are relevant to other agents, not the Ruby agent.

### CODE REVIEW

**Comment by estolfo** [comment]
jenkins retest this please

**Comment by mikker** [comment]
This is waiting on API stabilisation from APM Server, right?

**Comment by estolfo** [comment]
I'm waiting to find out if not including the stacktrace for chained exceptions, and only at the top-level, is ok with the UI.
Ref: https://github.com/elastic/kibana/issues/43701

The other questions in the above Kibana ticket are relevant to other agents, not the Ruby agent.

**Comment by estolfo** [comment]
Update: The [linked kibana issue](https://github.com/elastic/kibana/issues/43701) has been closed citing no issue if no stacktrace is included for nested chained exceptions.
I'll rebase and then merge this, if you approve @mikker 
There are no code changes since the original https://github.com/elastic/apm-agent-ruby/pull/481

**Pull request merged**
