### PR TITLE
Add transaction and span outcome cucumber specs

### PR DESCRIPTION
**Pull request by estolfo**

### CODE REVIEW

**Comment by mikker** [comment]
This actually took a lot less stepdefs than I was expecting. Good job!

**Comment by mikker** [comment]
Is this blocked btw?

**Comment by estolfo** [comment]
Yes, we mentioned it briefly at the agents meeting last week-- Sylvain will look over the the PR [here](https://github.com/elastic/apm/pull/402) and make some suggestions. So I'm waiting until that PR is settled, as this one may change as a result.

**Comment by estolfo** [comment]
Closing in favor of #966

**Pull request closed without merging**
