### PR TITLE
Update benchmark script

### PR DESCRIPTION
**Pull request by mikker**
The benchmark spins up a tiny Rails app with one endpoint that does one db query, then sends 10.000 requests through it _with_ the agent and then _without_ the agent.

### CODE REVIEW

**Comment by axw** [comment]
@mikker I think it would be more useful to see something like the Java agent's benchmarks:

https://github.com/elastic/apm-agent-java/blob/62acdb1f349474ade1fe037e10bfbe803e7ca580/apm-agent-benchmarks/src/main/java/co/elastic/apm/agent/benchmark/ElasticApmContinuousBenchmark.java#L60

This is a simplistic servlet (HTTP request handler) which ones a single SQL query. A servlet is constructed, and then requests are passed through it and statistics gathered to measure the overhead with and without the agent enabled.

The Go agent does something similar, but I measure the HTTP and SQL instrumentation independently.

**Comment by kuisathaverat** [comment]
When it is finished ping us to add the logic to send the bulk files to an Elasticsearch.

**Comment by mikker** [comment]
Ready now, @kuisathaverat 🙏

**Comment by kuisathaverat** [comment]
we did it now https://github.com/elastic/apm-agent-ruby/blob/master/Jenkinsfile#L269-L270 so you can check the benchmarks at kibana

**Pull request merged**
