### PR TITLE
Add test for capture_headers in context_builder

### PR DESCRIPTION
**Pull request by mheiligers-godaddy**
## What does this pull request do?

[PR#1405](https://github.com/elastic/apm-agent-ruby/pull/1405) introduced a bug where if `capture_headers` is `false`, the `ContextBuilder` will raise "undefined method `has_key?' for nil:NilClass"

## Checklist

- [x] I have signed the [Contributor License Agreement](https://www.elastic.co/contributor-agreement/).
- [x] My code follows the style guidelines of this project (See `.rubocop.yml`)
- [x] I have rebased my changes on top of the latest main branch

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing [**unit** tests](https://github.com/elastic/apm-agent-ruby/blob/main/CONTRIBUTING.md#testing) pass locally with my changes

~~- [ ] I have made corresponding changes to the documentation~~
- [x] I have updated [CHANGELOG.asciidoc](CHANGELOG.asciidoc)
~~- [ ] I have updated [supported-technologies.asciidoc](docs/supported-technologies.asciidoc)~~
~~- [ ] Added an API method or config option? Document in which version this will be introduced~~

### CODE REVIEW

**Comment by mheiligers-godaddy** [comment]
> ❌ Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement): [4fb1308](https://github.com/elastic/apm-agent-ruby/commit/4fb1308bb6884233d55755d86204dfcba4ac42d9)
> 
> Please, read and sign the above mentioned agreement if you want to contribute to this project

Yes, yes I have.

**Comment by estolfo** [comment]
Hi @mheiligers-godaddy thanks a lot for opening this PR! Are you sure you're signing the CLA with the same email address you use for this GitHub account?

**Comment by mheiligers-godaddy** [comment]
> Hi @mheiligers-godaddy thanks a lot for opening this PR! Are you sure you're signing the CLA with the same email address you use for this GitHub account?

Yes, but I got an email from @gtback yesterday afternoon saying the system had been updated (I didn't realize there was an additional step) so the check should pass now.

Separately, I see there's a failing spec on JRuby 9.2-13 with Rails 5.2, but it seems unrelated to my change, though I admit I haven't looked into it further than the stack trace in the action output.

**Review by estolfo — APPROVED** [review]

**Comment by reakaleek** [comment]
run docs-build

**Comment by sjohn-godaddy** [comment]
Could we have a release with this bug fix? that would be very welcome, as our other alternative is to downgrade to 4.3 (due to dependency to other gems)

**Comment by estolfo** [comment]
Hi @sjohn-godaddy, sure, we can do a release soon. Thanks for your patience!

**Comment by picandocodigo** [comment]
@sjohn-godaddy @mheiligers-godaddy [v4.7.3](https://github.com/elastic/apm-agent-ruby/releases/tag/v4.7.3) was released with this fix.

**Pull request merged**
