### PR TITLE
Scrub request body contents to remove illegal UTF-8 characters

### LINKED ISSUE #831: Scrub illegal utf-8 characters  from capture body
## Describe the bug
Workers are dying because JSON conversion is failing. The reason for this is that the capture body has illegal UTF-8 characters.

We use ```force_encoding``` method but that does not guarantee that all characters are UTF-8 encoded because there isn't 1-1 mapping for all characters between encoding formats/schemas. Basically when we use the above method we are asking ruby to read the string (sequence of bytes) using UTF-8 encoding table. This should be done when we are sure that these sequence of bytes are valid UTF-8 characters. I think it is right to assume all string have valid UTF-8 encoded character in rails but since we get data from outer world (browsers,API's etc) there is a possibility we end up with invalid UTF-8 characters in the string. Therefore I suggest that we scrub the string on invalid characters. 

The tradeoff here is that we loose some characters/data but we will still have metrics and logs for customer to take action that just letting the worker fail.

```E, [2020-07-11T03:40:45.077715 #21780] ERROR -- : [ElasticAPM] Failed converting event to JSON: <ElasticAPM::Transaction id:00fa080533576310 name:"Rack" type:"request">
E, [2020-07-11T03:40:45.077933 #21780] ERROR -- : [ElasticAPM] {:transaction=>{:id=>"00fa080533576310", :trace_id=>"2a05855ee082972625b082ab52d8532b", :parent_id=>nil, :name=>"Rack", :type=>"request", :result=>"HTTP 4xx", :duration=>2.552, :timestamp=>1594438845072913, :sampled=>true, :context=>{:custom=>{}, :tags=>{}, :request=>{:body=>"\u0000\u0003\u0000\u0000\u0000\u0001\u0000\u0000\u0000\u0000\xFF\xFF\xFF\xFF\u0011\n\a3sun.rmi.server.UnicastRef\u0000\v192.168.0.1\u0000\u0000\u0015\xB5\xF9jv{|\xDEhOvت=\u0000\u0000\u0001[\xB0L\u001D\x81\x80\u0001\u0000", :cookies=>{}, :env=>{"REQUEST_URI"=>"/test/endpoint", "PATH_INFO"=>"/test/endpoint", "SCRIPT_NAME"=>"", "QUERY_STRING"=>"", "REQUEST_METHOD"=>"POST", "SERVER_NAME"=>"127.0.0.1", "SERVER_PORT"=>"3000", "SERVER_SOFTWARE"=>"nginx/1.14.0 Phusion_Passenger/5.3.7", "SERVER_PROTOCOL"=>"HTTP/1.1", "REMOTE_ADDR"=>"127.0.0.1", "REMOTE_PORT"=>"58672", "CONTENT_TYPE"=>"application/x-amf", "CONTENT_LENGTH"=>"83", "PASSENGER_CONNECT_PASSWORD"=>"[FILTERED]", "ROUTES_47311647610260_SCRIPT_NAME"=>"", "ORIGINAL_FULLPATH"=>"/test/endpoint", "ORIGINAL_SCRIPT_NAME"=>""}, :headers=>{"User-Agent"=>"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:56.0) Gecko/20100101 Firefox/56.0", "Accept"=>"*/*", "Accept-Encoding"=>"gzip, deflate", "X-Forwarded-Server"=>"test.server", "X-Forwarded-Host"=>"192.168.0.1:80", "Host"=>"127.0.0.1:3000", "X-Forwarded-Proto"=>"http", "X-Forwarded-For"=>"192.168.0.2, 192.168.0.1", "Version"=>"HTTP/1.1"}, :http_version=>"1.1", :method=>"POST", :socket=>{:remote_addr=>"127.0.0.1", :encrypted=>false}, :url=>{:protocol=>"http", :full=>"http://192.168.0.1/test/endpoint", :hostname=>"192.168.0.1", :port=>"80", :pathname=>"/test/endpoint", :search=>"", :hash=>nil}}, :response=>{:status_code=>404, :headers=>{"Content-Type"=>"text/html; charset=utf-8", "Content-Length"=>"0", "X-Request-Id"=>"1c4a2faa-1949-4e26-9d2b-53de92825206", "X-Runtime"=>"0.002356"}, :headers_sent=>true, :finished=>true}, :user=>nil, :service=>nil}, :span_count=>{:started=>0, :dropped=>0}}}

```

## Steps to reproduce
Screen Shot 2020-07-14 at 11 41 03

## Expected behavior

Invalid characters should not be present in request body

## Environment

- **OS**: Linux
- **Ruby version**: 2.2.4
- **Framework and version**: rails 5.0.2
- **APM Server version**: 
- **Agent version**:3.6.0

### PR DESCRIPTION
**Pull request by Anasjabri**
## What does this pull request do?

Scrub request body contents to remove illegal UTF-8 characters

## Why is it important?
Because workers die with malformed format string 

## Checklist

- [x] I have signed the [Contributor License Agreement](https://www.elastic.co/contributor-agreement/). 
- [x] My code follows the style guidelines of this project (See `.rubocop.yml`)
- [x] I have rebased my changes on top of the latest master branch

- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing [**unit** tests](https://github.com/elastic/apm-agent-ruby/blob/master/CONTRIBUTING.md#testing) pass locally with my changes

- [x] I have made corresponding changes to the documentation
- [x] I have updated [CHANGELOG.asciidoc](CHANGELOG.asciidoc)
- [ ] I have updated [supported-technologies.asciidoc](docs/supported-technologies.asciidoc)
- [ ] Added an API method or config option? Document in which version this will be introduced

### CODE REVIEW

**Comment by mikker** [comment]
Hi @Anasjabri! This is great, would love to include it. Can you sign the CLA? Otherwise I can't merge.

jenkins, please run the tests

**Comment by mikker** [comment]
jenkins, please run the tests

**Comment by Anasjabri** [comment]
> Hi @Anasjabri! This is great, would love to include it. Can you sign the CLA? Otherwise I can't merge.

I did sign CLA multiple times. below is the pdf.Don't know why bot is not picking it up
[Please_DocuSign_Individual_Contributor_Licen (6).pdf](https://github.com/elastic/apm-agent-ruby/files/4983102/Please_DocuSign_Individual_Contributor_Licen.6.pdf)

**Comment by mikker** [comment]
The CLA machine sees you signed with _yournamemail_ @gmail – is that email also registered on you GH profile?

**Comment by Anasjabri** [comment]
> The CLA machine sees you signed with _yournamemail_ @ gmail – is that email also registered on you GH profile?

Yes
Screen Shot 2020-08-04 at 12 32 07

**Comment by gtback** [comment]
Hi @Anasjabri, thanks for contributing!

It looks like the first commit (0d8513bdac62a5c30be5fd7b717d1ea34cc83f44) was made using a different email address:

```
Author: Anas AlJabri <jabriana@cisco.com>
```

If you can do any of the following:
- Sign another CLA with that address,
- Rebase that commit and modify the author ([this StackOverflow answer](https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit#3042512) has some directions)
- Just squash all the commits into a single change with your Gmail address.
That should be enough to make our robot happy!

**Comment by mikker** [comment]
jenkins, please run the tests

**Comment by mikker** [comment]
Test failure is unrelated.

**Comment by mikker** [comment]
Thank you for contributing to the agent, @Anasjabri  💙💚💛💜❤️

**Pull request merged**
