### PR TITLE
Remove default framework and add env var in benchmark script

### PR DESCRIPTION
**Pull request by estolfo**
This removes a default framework in the `Gemfile` and adds a `FRAMEWORK` environment variable to the docker container running the benchmark tests.

### CODE REVIEW

**Comment by mikker** [comment]
@v1v It's unclear to me what actually failed in this CI run?

**Comment by estolfo** [comment]
The linter failed https://github.com/estolfo/apm-agent-ruby/commit/ed58635377b59d33c45c18ac0a293bc7322e0230/checks
but the result are empty and when I run `rubocop` locally, it passes. So 🤷🏻‍♀️

**Comment by v1v** [comment]
> regarding the linter

`spec/scripts/benchmarks.sh` got some end-of-file issue

https://apm-ci.elastic.co/blue/organizations/jenkins/apm-agent-ruby%2Fapm-agent-ruby-linting-mbp/detail/PR-632/2/tests

The sanity check stage does run the `pre-commit` command but the rubocop is not yet in place. 

What commands should I run for validating the rubocop? Then I can add it

**Comment by mikker** [comment]
I recently added a GH action for Rubocop that annotates the code directly on GH. I'd prefer to use that instead. See https://github.com/elastic/apm-agent-ruby/pull/627/files#diff-90829e76e906f1c73140c7ded7e1b268

**Pull request merged**
