### PR TITLE
Ensure that authentication/authorization material is also ignored

### PR DESCRIPTION
**Pull request by krainboltgreene**
The agent shouldn't be sending along Authorization or Authentication headers, keys, or params.

### CODE REVIEW

**Comment by mikker** [comment]
Thanks for this. Very reasonable suggestion, would love to merge it in. Can I make you sign our CLA so I can merge?

**Comment by mikker** [comment]
jenkins, test this please

**Comment by mikker** [comment]
@krainboltgreene Welcome back from the Holdidays 😄 did you have a chance to review the CLA?

**Comment by krainboltgreene** [comment]
@mikker Thanks for the reminder!

**Pull request merged**
