### PR TITLE
fix: wrong variable name

### PR DESCRIPTION
**Pull request by kuisathaverat**
## What does this pull request do?

* Fix a wrong variable name
* Add retries to `bundle`
* Add `/test` comment trigger

### CODE REVIEW

**Review by mikker — APPROVED** [review]

**Review by cachedout — APPROVED** [review]

**Comment by kuisathaverat** [comment]
> @kuisathaverat Is this still relevant? What's left for it to be done?

The Pipeline pass `IMAGE_NAME` not `RUBY_IMAGE` so `spec/scripts/spec.sh` is not working as expected. There is nothing to be done, I did not merge it because the CI is not green, even though the failures are not related to the PR.

**Pull request closed without merging**
