### PR TITLE
Support for erb style on config file

### PR DESCRIPTION
**Pull request by PedroSeda**
This PR adds support to erb styled variables on config file

[Issue 212](https://github.com/elastic/apm-agent-ruby/issues/212)

### CODE REVIEW

**Comment by PedroSeda** [comment]
> Hi @PedroSeda! This is wonderful – I see you found the issue too 😃 Thank you.
> 
> I like how Rails does this, only evaluating as ERB if the file is called `.yml.erb`. That'll also work better with peoples' editors' syntax highlighting (guessing). If file is just `.yml` we only load.
> 
> I think the config option stays `config_file: config/elastic_apm.yml` but we check programmaticaly if an ERB version exists.
> 
> Do you agree?

I might be wrong, but I think `credentials.yml`, `secrets.yml` and `database.yml` all support ERB tags without the `.erb` at the end. I think it's default to Rails, but it might not be to other frameworks.

**Comment by PedroSeda** [comment]
> We also need
> 
> * [ ]  Update the docs to mention this
> * [ ]  `require 'erb'` somewhere to be sure(?)
> * [ ]  Update the changelog
> 
> Would you like to do this? Then you are very welcome to get the credit. Otherwise let me know and I'll sail this safely to shore 🚢

Will do, I'll tackle that this afternoon

**Comment by PedroSeda** [comment]
I added an example using an ERB tag to the docs. Let me know if that's enough :smile:

**Comment by mikker** [comment]
Thanks! I added yet another note to the configuration section in the PR referenced.

**Comment by mikker** [comment]
Merged via https://github.com/elastic/apm-agent-ruby/pull/288.

**Pull request closed without merging**
