### PR TITLE
fix: rails master has been renamed to main

### PR DESCRIPTION
**Pull request by mdelapenya**
## What does this pull request do?
It renames the `rails-master` variable to `rails-main`

## Why is it important?
The CI is broken for both rails 3.0 and 2.7, which are not excluded in the CI support matrix.

## Checklist

- [x] I have signed the [Contributor License Agreement](https://www.elastic.co/contributor-agreement/). 
- [ ] My code follows the style guidelines of this project (See `.rubocop.yml`)
- [x] I have rebased my changes on top of the latest master branch

- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing [**unit** tests](https://github.com/elastic/apm-agent-ruby/blob/master/CONTRIBUTING.md#testing) pass locally with my changes

- [ ] I have made corresponding changes to the documentation
- [ ] I have updated [CHANGELOG.asciidoc](CHANGELOG.asciidoc)
- [ ] I have updated [supported-technologies.asciidoc](docs/supported-technologies.asciidoc)
- [ ] Added an API method or config option? Document in which version this will be introduced

### CODE REVIEW

**Review by cachedout — APPROVED** [review]

**Comment by mikker** [comment]
Great, thanks!

**Review by mikker — APPROVED** [review]

**Comment by mikker** [comment]
I actually thought GH would redirect. Perhaps Rails didn't do it the way GH intended 🤷‍♂️

**Comment by mdelapenya** [comment]
@mikker is this a real problem right with the framework version, right?

>[2021-01-26T07:15:46.087Z] [!] There was an error parsing `Gemfile`: Illformed requirement ["~> main.0"]. Bundler cannot continue.

Maybe it's not enough to simply change the branch, but we also have to maintain the gem version. wdyt?

**Review by kuisathaverat — APPROVED** [review]

**Comment by mikker** [comment]
We'll need to change `Gemfile` too probably, yes.

**Comment by mdelapenya** [comment]
Closing, as it's superseded by #940

**Pull request closed without merging**
