### PR TITLE
Adding missing links

### PR DESCRIPTION
**Pull request by insukcho**
## What does this pull request do?

The sub-links and API reference link is not visible. 
Align with the same page on Python Agent doc [here]( https://www.elastic.co/guide/en/apm/agent/python/current/set-up.html).

## Why is it important?

It will make the User find each subpage more easily and provide the same UX with other lang agent reference guide.

### CODE REVIEW

**Comment by mikker** [comment]
Thanks @insukcho! I've added @bmorelli25 as a reviewer as he knows a whole lot more about the docs setup than I do 😀

**Comment by mikker** [comment]
In the future, please fork the repo first before adding branches. This makes sure the _mother_ repo is nice and tidy 😊

**Comment by insukcho** [comment]
Thank you for the comments @mikker 

> In the future, please fork the repo first before adding branches.

I will definitely follow your guide, thanks.
By the way, I use `Edit` button on the right-top corner on documentation to create the branch easily. If recommending forking the repo first, do we still need `Edit` button that might let any user make this kind of branch again?

**Comment by mikker** [comment]
I don't think we have any say in whether GitHub shows Edit buttons but we can definitely stop ourselves from clicking them 😉

If you fork first, then browse your own fork, the edit functionality will commit to your own fork.

**Comment by insukcho** [comment]
> I don't think we have any say in whether GitHub shows Edit buttons but we can definitely stop ourselves from clicking them 😉

@mikker I'm not talking about any button on Github. The `Edit` button is in Elastic public documentation to allow any doc reader edit docs easily. If Elastic doesn't want to use it, we should remove those buttons.

**Comment by mikker** [comment]
I guess it's a combination of you being a member of the Elastic org on GH and clicking those edit buttons. Outside users will probably(?) be forced to fork first.

Anyway, thanks for the suggestion 😊

**Comment by insukcho** [comment]
@bmorelli25 Thanks for the approval of my modification. Just curious, how to get the preview link to check how my modification looks like?

**Comment by bmorelli25** [comment]
@insukcho great question. The preview is generated automatically on every PR. To access it, just use this template:
`http://{{REPO_NAME}}_{{PR_NUMBER}}.docs-preview.app.elstc.co/guide/`

**Pull request merged**
