### PR TITLE
[APM-CI][Ruby] Pipeline version 0

### PR DESCRIPTION
**Pull request by kuisathaverat**
* Pipeline support
* Parallel test
* Send benchmarks on master branch merge
* Build docs on master branch merge

image

### CODE REVIEW

**Comment by mikker** [comment]
jenkins, retest this please

**Comment by kuisathaverat** [comment]
jenkins, retest this please

**Comment by mikker** [comment]
@kuisathaverat What's the status here? Do I need to do anything?

**Comment by kuisathaverat** [comment]
@mikker it is ready to go if you don't have any objection we'd merge it tomorrow.

**Pull request merged**
